import Head from "next/head";
import styles from "../styles/Home.module.css";
import { withLayout } from "../src/Layout/Layout";
import {
  CardsCarousel,
  Carousel,
  CredirClalculator,
  CurrencyConverter,
  DailyLoan,
  InfoCards,
  News,
  Operations,
} from "../src/widgets";

function Home() {
  return (
    <>
      <Head>
        <title>Kapital Bank - Birinci Bank | Bütün Bank Xidmətləri</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Carousel />
        <Operations />
        <CardsCarousel />
        <DailyLoan />
        <CredirClalculator/>
        <InfoCards />
        <News />
        <CurrencyConverter/>
      </main>
    </>
  );
}
export default withLayout(Home);
